port: 5773

# 初次登录的root密码
initSuperAdministratorPassword: 1DiKmZQG-lAgQMQ23EeCbZbSqiqkbmS_zG6C2Xt96WMmh9tcIReWpMtNkIki3loT

authSecret: qAUdiRaz3x6DMzpXZGr_79Zd1WuBVepsftqK8CsMHRf3V9LBkdNJfS8eqcNdOuqP
refreshAuthSecret: qAUdiRaz3x6DMzpXZGr_79Zd1WuBVepsftqK8CsMHRf3V9LBkdNJfS8eqcNdOuqP

# OSS 配置
OSS_REGION: ''
OSS_ACCESSKEYID: ''
OSS_ACCESSKEYSECRET: ''
OSS_BUCKET: ''
